name: charadex
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.4.0
  vibration: ^3.1.3
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # aktiviert Code-Gen für die ARB-Dateien
  generate: true

  assets:
    - assets/images/startscreen_logo.png
    - assets/images/startscreen_title.png
    - assets/images/round_end.png
    - assets/topics/topic_car.png
    - assets/topics/topic_sport.png
    - assets/topics/topic_geography.png
    - assets/topics/topic_film.png
    - assets/topics/topic_animal.png
    - assets/topics/topic_jobs.png
    - assets/topics/topic_stars.png
    - assets/topics/topic_drugs.png
    - assets/topics/topic_music.png
    - assets/topics/topic_party.png
    - assets/topics/topic_serien.png
    - assets/topics/topic_sex.png
    - assets/sounds/ding.mp3
    - assets/sounds/buzz.mp3
    - assets/sounds/beep.mp3
    - assets/sounds/highbeep.mp3
    - assets/sounds/finish.mp3
    - assets/words/de.json
    - assets/words/en.json
    - assets/words/es.json
    - assets/words/hr.json
    - assets/words/zh.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
# Konfiguration für das Flutter L10n-Tool
