name: charadex
description: "A new Flutter project."
publish_to: "none"
version: 1.0.4+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  shared_preferences: ^2.2.2
  sensors_plus: ^3.0.0

  in_app_review: ^2.0.8
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # aktiviert Code-Gen für die ARB-Dateien
  generate: true

  assets:
    - assets/topics/animals.png
    - assets/topics/basketball.png
    - assets/topics/cars.png
    - assets/topics/football.png
    - assets/topics/geography.png
    - assets/topics/history.png
    - assets/topics/jobs.png
    - assets/topics/music.png
    - assets/topics/countries.jpeg
    - assets/topics/sex.jpeg
    - assets/topics/sport.jpeg
    - assets/topics/superheros.jpeg
    - assets/topics/tennis.jpeg
    - assets/topics/films/films.png
    - assets/topics/films/series.png
    - assets/topics/films/breakingbad.jpeg
    - assets/topics/films/disney.jpeg
    - assets/topics/films/harrypotter.jpeg
    - assets/topics/films/netflix.jpeg
    - assets/topics/films/paramount.jpeg
    - assets/topics/films/prime.jpeg
    - assets/tutorial/incorrect.png
    - assets/tutorial/correct.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
# Konfiguration für das Flutter L10n-Tool
