name: charadex
description: "A new Flutter project."
publish_to: "none"
version: 1.0.4+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # aktiviert Code-Gen für die ARB-Dateien
  generate: true

  assets:
    - assets/topics/animals.png
    - assets/topics/basketball.png
    - assets/topics/cars.png
    - assets/topics/films.png
    - assets/topics/football.png
    - assets/topics/geography.png
    - assets/topics/history.png
    - assets/topics/jobs.png
    - assets/topics/music.png
    - assets/topics/series.png
    - assets/topics/sport.png
    - assets/tutorial/incorrect.png
    - assets/tutorial/correct.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
# Konfiguration für das Flutter L10n-Tool
