# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# Supported language codes include:
# ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US",
#  "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it",
#  "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk",
#  "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
languages(['de-DE', 'en-US', 'es-ES', 'hr', 'zh-Hans'])

name({
  'default' => "GuessUp – Charades Game",
  'de-DE' => "GuessUp – Stirnraten Spiel",
  'en-US' => "GuessUp – Charades Game",
  'es-ES' => "GuessUp – Juego de Mímica",
  'hr' => "GuessUp – Igra Pantomime",
  'zh-Hans' => "GuessUp – 你来比划我来猜"
})

# optional, can't be longer than 30 characters
subtitle({
  'default' => "The Ultimate Party Game",
  'de-DE' => "Partyspiel für Gruppen",
  'en-US' => "Charades with Friends",
  'es-ES' => "Charadas con Amigos",
  'hr' => "Pantomima s Prijateljima",
  'zh-Hans' => "朋友聚会猜词游戏"
})

description({
  'default' => "GuessUp is the ultimate mobile charades game to liven up your party! Hold your phone on your forehead, guess the word from your friends' clues, and see who can score the most points. Perfect for families, friends, and parties!",
  'de-DE' => "GuessUp ist das ultimative Stirnraten-Spiel fürs Handy – perfekt für jede Party! Halte dein Handy an die Stirn, errate den Begriff anhand der Hinweise deiner Freunde und sammle Punkte. Ideal für Familienabende, Partys und Spieleabende!",
  'es-ES' => "GuessUp es el mejor juego de mímica para tu móvil. Pon el teléfono en la frente, adivina la palabra con las pistas de tus amigos ¡y gana! Perfecto para fiestas, familia y reuniones divertidas.",
  'hr' => "GuessUp je ultimativna igra pantomime za mobitel koja će oživjeti svaku zabavu! Drži telefon na čelu, pogađaj riječi prema tragovima prijatelja i osvoji što više bodova. Idealno za obitelj, prijatelje i zabave!",
  'zh-Hans' => "GuessUp 是最棒的手机猜词游戏，让你的派对嗨翻天！把手机放在额头上，根据朋友的提示猜出词语，看看谁能得最高分。非常适合家庭、朋友和派对场合！"
})

keywords({
  'default' => "charades, party game, guess, heads up, guessup, team game, word game, fun",
  'de-DE' => "Stirnraten, Charades, Partyspiel, Ratespiel, Freunde, Familie, lustig, GuessUp",
  'en-US' => "charades, guess up, party, fun, friends, guessing, heads up, team, word game",
  'es-ES' => "charadas, juego de fiesta, adivina, palabras, amigos, familia, mímica, diversión",
  'hr' => "pantomima, igra za zabavu, pogađanje, društvena igra, timska igra, zabavno, riječ",
  'zh-Hans' => "你来比划我来猜, 猜词游戏, 派对游戏, 家庭游戏, 朋友游戏, 字词游戏, 趣味游戏"
})

# TODO uncomment on second release
release_notes({
  'default' => "Bug fixes and stability improvements. Added a step-by-step tutorial to guide new users through the app’s features and onboarding process.",
  'de-DE' => "Fehlerbehebungen und Stabilitätsverbesserungen. Schritt-für-Schritt-Tutorial hinzugefügt, das neue Nutzer durch alle Funktionen und das Onboarding führt.",
  'en-US' => "Bug fixes and stability improvements. Added a step-by-step tutorial to guide new users through the app’s features and onboarding process.",
  'es-ES' => "Corrección de errores y mejoras de estabilidad. Añadido un tutorial paso a paso para guiar a los nuevos usuarios a través de las funcionalidades de la app y el proceso de incorporación.",
  'hr' => "Ispravljeni bugovi i poboljšana stabilnost. Dodan detaljan vodič korak po korak koji nove korisnike vodi kroz značajke aplikacije i proces pokretanja.",
  'zh-Hans' => "修复了已知问题并提升了稳定性。新增循序渐进教程，引导新用户了解应用功能和使用流程。"
})

privacy_url({
  'default' => 'https://vucak.at/en/guessup/data-protection',
  'de-DE' => 'https://vucak.at/en/guessup/data-protection',
  'es-ES' => 'https://vucak.at/en/guessup/data-protection',
  'hr' => 'https://vucak.at/en/guessup/data-protection',
  'zh-Hans' => 'https://vucak.at/en/guessup/data-protection'
})

support_url({
  'default' => 'https://vucak.at/en/contact',
  'de-DE' => 'https://vucak.at/de/contact',
  'es-ES' => 'https://vucak.at/es/contact',
  'hr' => 'https://vucak.at/hr/contact',
  'zh-Hans' => 'https://vucak.at/zh/contact'
})

# optional
promotional_text({
  'default' => "Improved, more stable, and fun as ever – GuessUp brings laughter to every party!",
  'de-DE' => "Verbessert, stabiler und spaßiger denn je – GuessUp sorgt für Lacher auf jeder Party!",
  'es-ES' => "¡Mejorado, más estable y tan divertido como siempre – GuessUp anima cualquier fiesta!",
  'hr-HR' => "Poboljšan, stabilniji i zabavniji nego ikad – GuessUp donosi smijeh na svaku zabavu!",
  'zh-Hans' => "更稳定、更好玩，GuessUp 让每场派对充满欢笑！"
})


privacy_url({
  'default' => 'https://vucak.at/en/guessup/data-protection',
  'de-DE' => 'https://vucak.at/en/guessup/data-protection',
  'es-ES' => 'https://vucak.at/en/guessup/data-protection'
})

support_url({
  'default' => 'https://vucak.at/en/contact',
  'de-DE' => 'https://vucak.at/de/contact',
  'es-ES' => 'https://vucak.at/es/contact'
})

app_review_information(
  first_name: "Sven",
  last_name: "Vucak",
  phone_number: "+43 650 3015204",
  email_address: "sven@vucak.at",
  demo_user: "",
  demo_password: "",
  notes: ""
)

copyright("#{Time.now.year} Vucak IT Solutions")

automatic_release false

submission_information({
  content_rights_contains_third_party_content: false
})
