// lib/data.dart

/// Menüeinträge mit ID, Name (für spätere interne Verwendung) und titleKey (für Lokalisierung)
const List<Map<String, dynamic>> menuItems = [
  {
    "id": "all",
    "name": "All",
    "titleKey": "menu_all",
    "isSelected": true,
  },
  {
    "id": "kids",
    "name": "Kids",
    "titleKey": "menu_kids",
    "isSelected": false,
  },
  {
    "id": "sport",
    "name": "Sport",
    "titleKey": "menu_sport",
    "isSelected": false,
  },
  {
    "id": "adult",
    "name": "18+",
    "titleKey": "menu_adult",
    "isSelected": false,
  },
  {
    "id": "films",
    "name": "Films",
    "titleKey": "menu_films",
    "isSelected": false,
  },
];

/// Bildthemen mit ID, Titel-Schlüssel für Übersetzung, zugehörigem Menüpunkt, Pfad und Wortliste
const List<Map<String, dynamic>> imageItems = [
  {
    "id": "animals",
    "label": "Animals",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/animals.png",
    "words": ["cat", "dog", "lion", "elephant", "horse"],
  },
  {
    "id": "basketball",
    "label": "Basketball",
    "fitMenuItemId": "sport",
    "imagePath": "assets/topics/basketball.png",
    "words": ["dribble", "shoot", "dunk", "hoop", "NBA"],
  },
  {
    "id": "cars",
    "label": "Cars",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/cars.png",
    "words": ["engine", "steering wheel", "tire", "brake", "dashboard"],
  },
  {
    "id": "football",
    "label": "Football",
    "fitMenuItemId": "sport",
    "imagePath": "assets/topics/football.png",
    "words": ["goal", "offside", "corner", "foul", "striker"],
  },
  {
    "id": "geography",
    "label": "Geography",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/geography.png",
    "words": ["continent", "river", "mountain", "desert", "ocean"],
  },
  {
    "id": "history",
    "label": "History",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/history.png",
    "words": ["ancient", "medieval", "renaissance", "revolution", "war"],
  },
  {
    "id": "jobs",
    "label": "Jobs",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/jobs.png",
    "words": ["teacher", "doctor", "engineer", "chef", "firefighter"],
  },
  {
    "id": "music",
    "label": "Music",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/music.png",
    "words": ["guitar", "piano", "concert", "melody", "orchestra"],
  },
  {
    "id": "countries",
    "label": "Countries",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/countries.jpeg",
    "words": ["Germany", "France", "China", "Brazil", "Canada"],
  },
  {
    "id": "sex",
    "label": "Sex",
    "fitMenuItemId": "adult",
    "imagePath": "assets/topics/sex.jpeg",
    "words": ["love", "romance", "passion", "seduction", "intimacy"],
  },
  {
    "id": "sport_general",
    "label": "Sport",
    "fitMenuItemId": "sport",
    "imagePath": "assets/topics/sport.jpeg",
    "words": ["athlete", "fitness", "competition", "team", "trophy"],
  },
  {
    "id": "superheros",
    "label": "Superheros",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/superheros.jpeg",
    "words": ["Superman", "Batman", "Spiderman", "Wonder Woman", "Hulk"],
  },
  {
    "id": "tennis",
    "label": "Tennis",
    "fitMenuItemId": "sport",
    "imagePath": "assets/topics/tennis.jpeg",
    "words": ["serve", "racket", "ace", "court", "match"],
  },
  {
    "id": "films",
    "label": "Films",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/films.png",
    "words": ["cinema", "director", "script", "actor", "popcorn"],
  },
  {
    "id": "series",
    "label": "Series",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/series.png",
    "words": ["episode", "season", "cliffhanger", "actor", "streaming"],
  },
  {
    "id": "breakingbad",
    "label": "Breaking Bad",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/breakingbad.jpeg",
    "words": ["Walter White", "meth", "Heisenberg", "chemistry", "New Mexico"],
  },
  {
    "id": "disney",
    "label": "Disney",
    "fitMenuItemId": "kids",
    "imagePath": "assets/topics/films/disney.jpeg",
    "words": ["Mickey", "Goofy", "Frozen", "Moana", "Aladdin"],
  },
  {
    "id": "disney",
    "label": "Disney",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/disney.jpeg",
    "words": ["Mickey", "Goofy", "Frozen", "Moana", "Aladdin"],
  },
  {
    "id": "harrypotter",
    "label": "Harry Potter",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/harrypotter.jpeg",
    "words": ["Hogwarts", "wizard", "wand", "quidditch", "Voldemort"],
  },
  {
    "id": "netflix",
    "label": "Netflix",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/netflix.jpeg",
    "words": ["stream", "series", "subscription", "binge", "originals"],
  },
  {
    "id": "paramount",
    "label": "Paramount",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/paramount.jpeg",
    "words": ["studio", "logo", "mountain", "Hollywood", "movies"],
  },
  {
    "id": "prime",
    "label": "Prime",
    "fitMenuItemId": "films",
    "imagePath": "assets/topics/films/prime.jpeg",
    "words": ["amazon", "stream", "membership", "series", "movies"],
  },
];
