source "https://rubygems.org"

gem "fastlane", ">= 2.226.0" # Always use the latest available version (or set to a specific version)
gem "dotenv"
# silence warnings "loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0."
gem "logger"
gem "mutex_m"
gem "abbrev"
gem "ostruct"

gem 'fastlane-plugin-flutter_version', '~> 1.0', '>= 1.0.1'
